name: Docker Image CI for GHCR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'beta'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username danielbrendel --password ${{ secrets.GH_CONTAINER_REGISTRY }} ghcr.io
          docker build . --tag ghcr.io/danielbrendel/hortusfox-web:latest --tag ghcr.io/danielbrendel/hortusfox-web:${{ github.ref_name }}
          docker push --all-tags ghcr.io/danielbrendel/hortusfox-web
